"""empty message

Revision ID: ea9bae5f180f
Revises: 86fbc68e08b7
Create Date: 2025-05-11 14:11:47.304462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9bae5f180f'
down_revision = '86fbc68e08b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.String(length=20), nullable=False),
    sa.Column('time', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('heart_rate', sa.Integer(), nullable=True),
    sa.Column('workout_date', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("sport IN ('Swimming', 'Cycling', 'Running')", name='valid_sport'),
    sa.CheckConstraint('distance > 0', name='positive_distance'),
    sa.CheckConstraint('heart_rate IS NULL OR (heart_rate >= 0 AND heart_rate <= 220)', name='valid_heart_rate'),
    sa.CheckConstraint('time >= 0', name='non_negative_time'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout')
    # ### end Alembic commands ###
